### ISSUE TITLE
Add mapping options (fielddata, multifield) on text field

### ISSUE THREAD

**Issue by gwintzer** [Orange-OpenSource/kibana-xlsx-import#1]
Hi,

In the mapping tab, when i choose a text-typed field, i'd like have options (like checkbox or radio button) to specify if the field :
- must be aggregatable (`fielddata: true`)
- must have a keyword multi-field (`{fields: {"keyword": {"type": "keyword"}}}`)

**Comment by kyushy** [comment]
Currently the plugin use keyword multi-field automaticaly when you choose "text" type. I will add those options for the next release.
