### ISSUE TITLE
Cannot resolve react-dom/server (kibana 6.6.0 compat)

### ISSUE THREAD

**Issue by wzulfikar** [Orange-OpenSource/kibana-xlsx-import#31]
I was checking if this repo is compatible with kibana 6.6.0. So, i forked it, made few adjustments (https://github.com/wzulfikar/kibana-xlsx-import/commit/1f726bda87a6a20beba5a6d59246788a822580f8), tried to upload csv, and everything works.

The thing is, to make it works, I had to install `react-dom`. Without installing `react-dom`, `kibana-plugin install` will fail:
```
Module not found: Error: Can't resolve 'react-dom/server'...
```
The error was triggered because below `ReactDOMServer` isn't resolvable:
https://github.com/Orange-OpenSource/kibana-xlsx-import/blob/c1dcef9c61e645c2611b88710c2eeb27aa9b3e33/public/components/mappingTable.js#L2

Upon checking `package.json`, I realized that `react-dom` is not installed. I went further to see if `react-dom` was installed transitively and it turns out that *it's* listed in elastic/eui, but as `devDependencies` ([elastic/eui#L145](https://github.com/elastic/eui/blob/e6e3168c7b988221388d480270ee058e5839a3a5/package.json#L145)).

My question is, is this error expected (due to lack of `react-dom` in package.json), or kibana-plugin is supposed to install `devDependencies` (so that `react-dom` is available via `elastic/eui`)?

Thanks for the awesome plugin, btw :)

> - edit 1 (Feb 27, 2019): add screenshot
---
Here's additional info to add more context.
- my 6.6.0 branch: https://github.com/wzulfikar/kibana-xlsx-import/tree/6.6.x
- zip file: https://github.com/wzulfikar/kibana-xlsx-import/releases/download/6.6.0/kibana-xlsx-import-6.6.0-1.zip

And here's images on how it looks like in kibana 6.6.0.

importing csv:
![screenshot from 2019-02-27 02-37-21](https://user-images.githubusercontent.com/7823011/53437601-e1a86580-3a38-11e9-8697-90ae5a0e6648.png)

csv imported:
![screenshot from 2019-02-27 02-38-10](https://user-images.githubusercontent.com/7823011/53437605-e40abf80-3a38-11e9-8e84-39b613e6a9f0.png)

**Comment by gwintzer** [comment]
Hello.

Thank you for your branch. I merged your diff ! :)

Concerning the missing react-dom/server dependancy, I think that the import statement is not useful.
Next time, I'll do some tests to remove it completly

**Comment by wzulfikar** [comment]
My pleasure :)
