### ISSUE TITLE
Typo, Presentation... : proposals

### ISSUE THREAD

**Issue by pchanas** [Orange-OpenSource/kibana-xlsx-import#6]
PLugin title (XLSX Import) is not really a title and not aligned with any Kibana title (lot of different titles in Kibana btw)
In French replace "convertir" by sthg more accurate
(?) following "ID dans elasticsearch" is too big compare to space left between lines
Put some space betwwen what you can change eg mapping and mandatory fields

**Comment by gwintzer** [comment]
#10

**Comment by gwintzer** [comment]
The UI deeply changed with the changes of version 6.3+
