### ISSUE TITLE
Error loading UTF 8 CSV Files

### ISSUE THREAD

**Issue by pchanas** [Orange-OpenSource/kibana-xlsx-import#7]
Hi
I tried to load UTF8 files, and I got some issues with French accents.

![image](https://user-images.githubusercontent.com/20401795/36732468-2d47841a-1bce-11e8-9c8a-e3d449d312eb.png)

P.

**Comment by kyushy** [comment]
All csv files are now read as UTF8
https://github.com/kyushy/kibana-xlsx-import/commit/a9a2492eecd01464dcc47d3db6e4d48066061626
